import type { Metadata } from "next";
import "./globals.css";
import {Header} from "@/app/_components/Header";
import Sidebar from "@/app/_components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex">
        <Sidebar />
        <div className="flex-1">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
